name: Terraform Base Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws-access-key-id:
        required: true
        type: string
      aws-secret-access-key:
        required: true
        type: string
      commands:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  terraform-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-terraform
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Terraform Commands
        uses: ./.github/actions/terraform-commands
        with:
          commands: ${{ inputs.commands }}